### ISSUE TITLE
No completion in just opened terminal

### ISSUE THREAD

**Issue by TeddyDD** [jorgebucaran/hydro#10]
Sometimes (around once in twenty cases) when the terminal is opened, there are no autosuggestion until you press enter at least once.  On attached git I'm typing different commands that should trigger autosuggestion:
![hydro-bugs](https://user-images.githubusercontent.com/4397533/111678318-7187fa80-8820-11eb-9be5-9a9a64573253.gif)

**Comment by jorgebucaran** [comment]
I don't see how Hydro could be interfering with Fish completions and I haven't seen anything like this since I started using it.

**Comment by TeddyDD** [comment]
It doesn't happen when using other prompts. I'll try to grab a trace and get back to you.

**Comment by jorgebucaran** [comment]
Thanks. Make sure you are also running the latest Fish.
