### ISSUE TITLE
Stash indicator

### ISSUE THREAD

**Issue by Arelav** [jorgebucaran/hydro#13]
Hey. Looks awesome.
Can stash indicator be added?
Some prompts just show it's something in git stash and some shows how many stashes created.
This is how it was done in Pure https://github.com/pure-fish/pure/pull/239/files

**Comment by jorgebucaran** [comment]
I considered adding a stash indicator at some point, but since I rarely use the stash, I didn't follow through. 

If more people want it, I guess, why not?

**Comment by jorgebucaran** [comment]
If you feel like working on this and sending me a PR, I'll definitely take a look.
