### ISSUE TITLE
Symbol issues

### ISSUE THREAD

**Issue by kidonng** [jorgebucaran/hydro#16]
- Mode prompt lacking symbol for `replace` mode, which is presented in [Fish's default mode prompt](https://github.com/fish-shell/fish-shell/blob/678fa2e6a9a9319f270f71ae5d3a7e14fd54bc21/share/functions/fish_default_mode_prompt.fish), is this intended?
- Pipestatus separator `ǀ` doesn't look good with JetBrains Mono on kitty, can this be changed to standard `|` or made configurable?
  ![image](https://user-images.githubusercontent.com/44045911/118130753-51e00d80-b430-11eb-8f2a-49801b1a6fdc.png)
  EDIT: looks like this is already reported in #15

**Comment by jorgebucaran** [comment]
> Mode prompt lacking symbol for replace mode, which is presented in Fish's default mode prompt, is this intended?

I'm not really sure. Maybe there's a bug in

https://github.com/jorgebucaran/hydro/blob/d9b07be4686cb0a84ac80c042c5786626ea6d7a1/functions/fish_mode_prompt.fish#L1-L21

> Pipestatus separator ǀ doesn't look good with JetBrains Mono on kitty...

Making the pipe symbol configurable sounds reasonable.

**Comment by kidonng** [comment]
> > Mode prompt lacking symbol for replace mode, which is presented in Fish's default mode prompt, is this intended?
> 
> I'm not really sure. Maybe there's a bug in
> 
> https://github.com/jorgebucaran/hydro/blob/d9b07be4686cb0a84ac80c042c5786626ea6d7a1/functions/fish_mode_prompt.fish#L1-L21
> 
> > Pipestatus separator ǀ doesn't look good with JetBrains Mono on kitty...
> 
> Making the pipe symbol configurable sounds reasonable. 

```diff
- case replace_one
+ case replace replace_one
```

**Comment by jorgebucaran** [comment]
If you are a vi mode user and this works for you, please send me a PR.
