### ISSUE TITLE
Feature request: support for fish_prompt_pwd_dir_length

### ISSUE THREAD

**Issue by giorgiga** [jorgebucaran/hydro#18]
The default fish prompt has a variable `fish_prompt_pwd_dir_length` which tells if and how much to shorten directory names when printing pwd in the prompt, while hydro seems to always shorten directories to 1 character.

Would you consider implementing this functionality in hydro?

BTW: it may even be possible to just use the default `pompt_pwd` function from inside hydro (see https://fishshell.com/docs/current/cmds/prompt_pwd.html and/or `functions prompt_pwd`)

**Comment by jorgebucaran** [comment]
Sounds reasonable. PR welcome.
