### ISSUE TITLE
"error: process ID out of range" when in git directories

### ISSUE THREAD

**Issue by Rush** [jorgebucaran/hydro#19]
I am getting this error whenever I enter a git directory using the hydro shell:
```
 error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
```

**Comment by jorgebucaran** [comment]
Is `hydro_fetch` enabled? If so, maybe there's something misplaced in your `config.fish`. Hydro doesn't use `ps`. 

Are you also running the latest version of Fish?

**Comment by Rush** [comment]
Yes latest but you could be right that maybe I had something misplaced. Unfortunately the easiest solution was to remove hydro and write my own prompt. Sorry for the confusion.
