### ISSUE TITLE
Issues with job control

### ISSUE THREAD

**Issue by nezirus** [jorgebucaran/hydro#22]
After latest updates I have funky problems with various apps and job control (when using fg builtin). I have a habit of suspending vim, running something in terminal, and returning back with fg. It took a while to notice that vim was "crashing". Some quick testing suggests it happens with other applications, so it's not vim's fault.

### Steps to reproduce

`> touch empty_file.txt`
`> less empty_file.txt` CTRL + Z from less
`fish: Job 1, 'less empty_file.txt' has stopped`
`> fg`
`Send job 1, “less empty_file.txt” to foreground` CTRL + Z from less
`fish: Job 1, 'less empty_file.txt has stopped`

Program is killed by shell after the second suspend...

When I remove hydro plugin the problem doesn't show up anymore.
My plugin list is:
- jethrokuan/z
- jorgebucaran/replay.fish
- franciscolourenco/done
- jorgebucaran/hydro

**Comment by jorgebucaran** [comment]
We'll need to roll back https://github.com/jorgebucaran/hydro/commit/e5f98b8770866b1c244a0e8415fd02a7722f71c5 then.

cc @brandonpittman

**Comment by jorgebucaran** [comment]
We'll need to roll back https://github.com/jorgebucaran/hydro/commit/e5f98b8770866b1c244a0e8415fd02a7722f71c5 then (FYI @brandonpittman).

**Comment by brandonpittman** [comment]
@jorgebucaran 

![CleanShot 2021-11-01 at 09 24 52@2x](https://user-images.githubusercontent.com/967145/139606549-75b1ee50-6e9e-430c-82c7-b17544318622.png)

😢 Well, back to sadness.

**Comment by brandonpittman** [comment]
And running `jobs` triggers the same thing.

![CleanShot 2021-11-01 at 09 32 24@2x](https://user-images.githubusercontent.com/967145/139606910-0cb41f06-7d3e-4955-bb18-67a8f61f1912.png)

**Comment by brandonpittman** [comment]
@jorgebucaran I forked the repo, dropped the last commit, and will just make do with that. 😄

**Comment by jorgebucaran** [comment]
I'll try to find a way to make this work both ways and let you know. 👍
