### ISSUE TITLE
Feature Request: Enable Prompt on the next line ala Spaceship

### ISSUE THREAD

**Issue by boris-kuz** [jorgebucaran/hydro#24]
Great theme, the asynchronous git status is a godsend.

See title! Would really love this. I have a little workaround by adding `\n` to the symbol, but this breaks sometimes with error messages etc.

**Comment by jorgebucaran** [comment]
Thank you @boris-kuz. Is this a dupe of #21?

**Comment by boris-kuz** [comment]
Oh yes it is! Sorry about that, I completely missed it.
Thanks for the quick response :)
