### ISSUE TITLE
Prompt doesn't handle ' in path

### ISSUE THREAD

**Issue by giorgiga** [jorgebucaran/hydro#27]
Just noticed this, thanks to the "Sid Meier's Civilization VI" folder:

    ~ ❱ mkdir "a'b"
    ~ ❱ cd a\'b/
    ~/ab\x1b[0m \x1b[0m\x1b[0m❱\x1b[0m

**Comment by jorgebucaran** [comment]
Nice catch! We need to stop using string unescape in `fish_prompt`.

**Comment by jorgebucaran** [comment]
Any luck coming up with a workaround for this @giorgiga?  🤔

**Comment by giorgiga** [comment]
I hadn't actually looked at the code :grin: 
I'll do it and submit a PR if I can figure things out (or comment here with my findings if I can't)

**Comment by giorgiga** [comment]
Ok, so... based on these assumed answers:

1. It serves no purpose: delete it
2. it serves no purpose: delete it
3. the first highlights the "main" directory (the current one or the one of the git repo we are in), the second one dims the path separators

I've rewritten `_hydro_pwd` and `fish_prompt`: please take a look at https://github.com/giorgiga/hydro/commit/db824408da4d02cdb4e7dc0ccdbe2b9e7df4d094 and let me know what you think (personally, I'd like to make the dimming of path separators configurable too, but I wanted to hear what you say first)

**Comment by giorgiga** [comment]
Read the code again after a pause.

The `string replace --all --regex -- "^.*/" ""` bit extracts the last path element from the git root directory path (ie. the same function as `filename`) and then that specific element is searched for and replaced with a colon further down (`string replace -- "/$root/" /:/`)... seems like this would cause problems if the git root directory name is not unique in the path (eg. `/home/user/work/project/work`). I think the sketched implementation in my copy of the repo, where PWD is explicitly split into three pieces, could be an improvement over this. 

The last line (`test "$root" != "$_hydro_git_root" && set --global _hydro_git_root $root && set $_hydro_git`) is still beyond my comprehension... it looks like `$root` is not defined there and so the code just resets `_hydro_git_root` and the variable whose name is contained in `_hydro_git` whatever `_hydro_git_root` is not empty, but (unless I am mistaken) that is the only place `_hydro_git_root` ever receives a value and so... it's always a noop? IDK it's too late at night to say :grin:

**Comment by giorgiga** [comment]
Removing `string unescape` seems to solve the problem, but... hadn't it been added for some reason in the first place?

Anyway if there's no need for additional investigation and no interest in extended functionality, I guess waiting for my PR will only slow you down... there's still stuff I don't understand about the code (eg. `hydro_color_pwd` vs `_hydro_color_pwd`) and it would take a while.

**Comment by jorgebucaran** [comment]
Was added to unescape hardcoded ANSI escape codes. I was trying to save space, but as we can see now it was pointless.

**Comment by jorgebucaran** [comment]
Fixed in 83c6f26a9951cf97af9dc05c214bf04ea04f3780.
