### ISSUE TITLE
Pre/Post prompt customization

### ISSUE THREAD

**Issue by mattmc3** [jorgebucaran/hydro#34]
@jorgebucaran - Are you open to a PR that would introduce two new variables into the prompt: a pre-prompt and a post-prompt like so...

```fish
set --query hydro_pre_prompt || set --global hydro_pre_prompt ""
set --query hydro_post_prompt || set --global hydro_post_prompt " "
```

The intent of the `hydro_pre/post_prompt` variables would be to allow users some to way to customize their prompt without having Hydro have to directly support all the customizations a user might dream up. For example, I like a more spacious prompt similar to [Zsh's Pure](https://github.com/sindresorhus/pure), so I could get that by setting the pre-prompt variable to a new line in my config like so: `set --global hydro_pre_prompt "\n"`.

Theoretically, with these variables a user could do whatever they wanted like adding a low battery indicator 🔋, or a python symbol 🐍 when they're in a python venv, or whatever - all without having to modify hydro itself. I'm open to other ideas on an implementation - just thought this would be a real simple change that would give the user more power in customizing their Hydro prompt.

The only change to Hydro in the PR to implement this would be adding those variables and then changing the `fish_prompt` function:

```fish
function fish_prompt
    echo -e "$hydro_pre_prompt...all-the-other-vars...$hydro_post_prompt"
end
```

**Comment by jorgebucaran** [comment]
@mattmc3 What would you like to set these to in practice? I just want to see how the prompt would look.

**Comment by mattmc3** [comment]
<img width="738" alt="Screen Shot 2022-06-17 at 9 29 27 PM" src="https://user-images.githubusercontent.com/978625/174417244-46cac0b6-7c8e-4d8c-bbb7-bc6a950c945a.png">

**Comment by mattmc3** [comment]
One more example using a post-prompt for to indicate a Python venv:

```fish
function VIRTUAL_ENV --on-variable VIRTUAL_ENV
    if test -n "$VIRTUAL_ENV"
        set -g fish_prompt_pwd_dir_length 1
        set --global hydro_pre_prompt ""
        set --global hydro_post_prompt "🐍 "
        set --global hydro_multiline false
    else
        set -g fish_prompt_pwd_dir_length -1
        set --global hydro_pre_prompt "\n"
        set --global hydro_post_prompt " "
        set --global hydro_multiline true
    end
end && VIRTUAL_ENV
```

<img width="962" alt="Screen Shot 2022-06-17 at 9 50 33 PM" src="https://user-images.githubusercontent.com/978625/174417852-94684e4f-fee1-4f36-b5c9-a7e53499c883.png">

**Comment by jorgebucaran** [comment]
Thanks, @mattmc3. Would this feature also supersede `hydro_multiline`?

**Comment by mattmc3** [comment]
It could. In that case we'd need to deprecate the multiline variable, and then if you wanted a more spacious prompt you'd do `set --query hydro_pre_prompt || set --global hydro_pre_prompt "\n\n"`. Since deprecating a variable would be a breaking change, I'll leave that call to you.

**Comment by mattmc3** [comment]
See PR #36 for an alternative implementation that handles mutiline support.

**Comment by jorgebucaran** [comment]
Thank you, @mattmc3. I'm still not sure if I want to add this feature, but I'm thinking about it. 

Question. Would a new "sparse" (as opposed to "compact") configuration variable solve your use case here? I'm not suggesting we add that yet, just curious.

**Comment by jorgebucaran** [comment]
Fair enough. Should we also consider adding a right prompt?

**Comment by jorgebucaran** [comment]
Perhaps a more flexible alternative would be introducing a new variable: `$hydro_prompt_items`. We would iterate over the list of items and figure out how to print the prompt from there. This would allow you not only to add new items, but to reorder the built-in items.

```fish
set --global hydro_prompt_items _hydro_git _hydro_pwd _hydro_prompt
```

```fish
function fish_prompt --description Hydro
    if set --query hydro_prompt_items
        set --local prompt 
        for item in $hydro_prompt_items
            switch $item
                case _hydro_pwd
                    set prompt "$prompt$_hydro_color_pwd$_hydro_pwd$hydro_color_normal"
                case _hydro_git
                    set prompt "$prompt $_hydro_color_git$$_hydro_git$hydro_color_normal"
                case _hydro_cmd_duration
                    set prompt "$prompt$_hydro_color_duration$_hydro_cmd_duration$hydro_color_normal"
                case _hydro_prompt
                    set prompt "$prompt$_hydro_prompt$hydro_color_normal"
                case \*
                    echo set prompt "$prompt$_hydro_color_$$item$$item$hydro_color_normal"
            end
        end
        echo -e "$prompt "
    else
        echo -e "$_hydro_color_pwd$_hydro_pwd$hydro_color_normal $_hydro_color_git$$_hydro_git$hydro_color_normal$_hydro_color_duration$_hydro_cmd_duration$hydro_color_normal$_hydro_prompt$hydro_color_normal "
    end
end
```

```console
main ~/C/@/hydro 1.3s ❱
```

**Comment by mattmc3** [comment]
I like that a lot. That’s a way better solution. Then the user just adds items, or overrides the prompt and displays the items themselves.

**Comment by jorgebucaran** [comment]
I'm not sure about this particular implementation yet, though. It's not slow, but it hurts perf a tiny bit, which I'd like to avoid or diminish somehow (if possible).

**Comment by jorgebucaran** [comment]
I think that's how [Tide](https://github.com/IlanCosman/tide) does it. I don't want to allow too much customization, though. I think Tide already excels at that. 

Having said that, I'm not sure about this particular implementation yet. It's not slow, but it hurts perf a tiny bit, which I'd like to avoid or diminish somehow (if possible).

**Comment by jorgebucaran** [comment]
While I'm open to exploring the idea of addons, components, or whatever we want to call them (#37), I won't be introducing specific pre/post customization variables, so closing as not planned.
