### ISSUE TITLE
Background on the keys representing the vi mode

### ISSUE THREAD

**Issue by guilhermedeandrade** [jorgebucaran/hydro#39]
I've recently started to use `hydro` and I'm really enjoying it! One thing that is bothering me is the fact that there is a background on some vi modes, namely `insert` and `normal`:

<img width="109" alt="image" src="https://user-images.githubusercontent.com/8797405/187970912-f06e757f-fa79-44a4-a0e6-6f5cbca7a9c3.png">

<img width="103" alt="image" src="https://user-images.githubusercontent.com/8797405/187970974-72816184-670d-4011-9775-f99ae8d7fe1f.png">

<img width="127" alt="image" src="https://user-images.githubusercontent.com/8797405/187971017-a91bd758-3307-48f0-908b-105272413de4.png">

<img width="201" alt="image" src="https://user-images.githubusercontent.com/8797405/187971048-a3343224-8b5d-43a7-ace7-627bf4f5b702.png">

I checked my config, but I couldn't find anything strange.

```fish
set -gx PNPM_HOME "$HOME/Library/pnpm"

# hydro
set -g hydro_multiline true
set -g fish_prompt_pwd_dir_length 0

fish_add_path /opt/homebrew/bin
fish_add_path PNPM_HOME 

if status is-interactive
    set fish_greeting "🌸"
    fish_vi_key_bindings
end
```

Environment details:

- Shell: fish, version 3.5.1
- Terminal: kitty, version 0.26.1
- Hydro: don't know how to check the version, but I ran `fisher update` few minutes ago

**Comment by jorgebucaran** [comment]
Vi mode colors and background colors are set here:

https://github.com/jorgebucaran/hydro/blob/d4c107a2c99d1066950a09f605bffea61fc0efab/functions/fish_mode_prompt.fish#L3-L19

**Comment by guilhermedeandrade** [comment]
> Vi mode colors and background colors are set here:
> 
> https://github.com/jorgebucaran/hydro/blob/d4c107a2c99d1066950a09f605bffea61fc0efab/functions/fish_mode_prompt.fish#L3-L19

Oh ok, thanks for the info!

**Comment by 2-4601** [comment]
BTW, it seems that `$fish_color_match` is deprecated: https://github.com/fish-shell/fish-shell/commit/f94a6a74f0e826db862e9381e505a4024bf02691

I don't know if @guilhermedeandrade asked for this but would be nice to have those colors modifiable via `$hydro_color_` variables. :)

**Comment by guilhermedeandrade** [comment]
@2-4601 that's really strange, because `$fish_color_match` totally fixed my issue 🤔 

```fish
function fish_mode_prompt
    if test "$fish_key_bindings" != fish_default_key_bindings
        set --local vi_mode_color
        set --local vi_mode_symbol
        switch $fish_bind_mode
            case default
                set vi_mode_color (set_color $fish_color_match)
                set vi_mode_symbol N
            case insert
                set vi_mode_color (set_color $fish_color_match)
                set vi_mode_symbol I
            case replace replace_one
                set vi_mode_color (set_color $fish_color_match)
                set vi_mode_symbol R
            case visual
                set vi_mode_color (set_color $fish_color_match)
                set vi_mode_symbol V
        end
        echo -e "$vi_mode_color $vi_mode_symbol \x1b[0m "
    end
end
```

**Comment by 2-4601** [comment]
Perhaps you are using a theme that still uses that variable? Or if the variable is not set then it won't display any color which is perhaps what you want? In any case, Fish shell itself does not use that variable anymore.

**Comment by guilhermedeandrade** [comment]
> Perhaps you are using a theme that still uses that variable? Or if the variable is not set then it won't display any color which is perhaps what you want? In any case, Fish shell itself does not use that variable anymore.
> 
> In a clean install of Fish
> 
> ```shell
> set --show fish_color_match
> ```
> 
> prints nothing.

It prints nothing here as well 😮 

![image](https://user-images.githubusercontent.com/8797405/188165433-86652f51-41bb-4d22-9530-e1dee23b414d.png)
