### ISSUE TITLE
Coloring of pwd

### ISSUE THREAD

**Issue by dnmct** [jorgebucaran/hydro#40]
How did you achieve that only the current folder and the git root are colored? Those two get rendered bold, but everything has color.

**Comment by jorgebucaran** [comment]
What did you try?

**Comment by asnelzin** [comment]
I've tried `set -U hydro_color_pwd "bryellow"` but this changes all pwd color to yellow, except last part is bold. Can you please make color of the last part configurable?

**Comment by jorgebucaran** [comment]
Here's what I have in my config.fish for Hydro. I hope this is what you are looking for.

```fish
set hydro_color_pwd $fish_color_command
set hydro_color_git $fish_color_command
set hydro_color_error $fish_color_error
set hydro_color_prompt --dim $fish_color_command
set hydro_color_duration --dim $fish_color_command
```
