### ISSUE TITLE
Show rust versions, etc.

### ISSUE THREAD

**Issue by KSaiAkshit** [jorgebucaran/hydro#48]
Sorry if i am missing something obvious. I really like using Hydro. Would it be possible to display rust package versions like `starship` does? 
![image](https://github.com/jorgebucaran/hydro/assets/44054643/2c4162b6-38cb-43fe-bedd-e65d6d4b5286)

**Comment by jorgebucaran** [comment]
Right now, you can't do this with the current setup. I've been tinkering with an [add-on system](https://github.com/jorgebucaran/hydro/pull/37) idea that might allow for this, but it's a lot of work. My current approach isn't really cutting it, so I've decided to shelve that for now. I might pick it back up again down the road, but don't hold your breath.

The thing about Hydro is, it's stripped down to the basics. That's what makes it so fast and efficient - it's built for folks who really know their way around. If you want something that works like a charm, without giving up much (if at all) you might want to check out Tide. And heads up, if you're using Fish, Starship might not be your best bet. It's not designed with Fish in mind like Tide is.

**Comment by jorgebucaran** [comment]
Right now, you can't do this with the current setup. I've been tinkering with an [add-on system](https://github.com/jorgebucaran/hydro/pull/37) idea that might allow for this, but it's a lot of work. My current approach isn't really cutting it, so I've decided to shelve that for now. I might pick it back up again down the road, but don't hold your breath.

The thing about Hydro is, it's stripped down to the basics. That's what makes it so fast and efficient - it's built for folks who really know their way around. If you want something that works like a charm, without giving up much (if at all) you might want to check out [Tide](https://github.com/ilancosman/tide). And heads up, if you're using Fish, Starship might not be your best bet. It's not designed with Fish in mind like Tide is.
