### ISSUE TITLE
mono repository

### ISSUE THREAD

**Issue by TeddyDD** [jorgebucaran/hydro#5]
Slightly off-topic :slightly_smiling_face: 

Since github.com/fishpkg/fish-prompt-mono redirects here: do you happen to have a copy of github.com/fishpkg/fish-prompt-mono repository laying somewhere? Could you send it to me or upload somewhere? Thanks :)

**Comment by jorgebucaran** [comment]
Hydro is the continuation of and successor to Mono, hence the redirect. For the old Mono, you can look at some of the [forks](https://github.com/jorgebucaran/hydro/network/members) still in existence. Unfortunately, they will not work with the latest Fisher, as many of the required dependencies are no longer available.
