### ISSUE TITLE
additional variables to customize prompt

### ISSUE THREAD

**Issue by XelorR** [jorgebucaran/hydro#51]
It would be nice to have some "blank" variables which can be used to add user-defined functionality. 

You can always add your functionality like this:
```fish
functions --copy fish_prompt fish_prompt_origin
function fish_prompt
    echo -n \n"$os_icon "
    fish_prompt_origin
end
```
in your config.fish

But what if you want to add git branch icon?
You can edit fish_prompt.fish or row 95 in hydro.fish, but it would be much better to just use specific variable for it.

I think following variables would be useful:

hydro_prompt_prefix
hydro_prompt_suffix
hydro_pwd_prefix
hydro_pwd_suffix
hydro_git_prefix
hydro_git_suffix
hydro_duration_prefix
hydro_duration_suffix

Or maybe prefixes only are enough. 

It can use existing colors for simplification.
E.g. hydro_pwd_prefix could be colored by hydro_color_pwd.

It can be used to add icons or additional user-defined functionality.

**Comment by jorgebucaran** [comment]
Is this just static text, not dynamic (#37)? If that's the case, I don't see how it could pose a performance issue, so I am okay with it. 👍

**Comment by XelorR** [comment]
Not dynamic. Main idea is to keep it fast and simple but more flexible if someone wants to add icons, decorations or results of their own functions.

**Comment by XelorR** [comment]
https://github.com/jorgebucaran/hydro/compare/main...XelorR:hydro:prefix_vars

Tried to implement but passing additional variable before git branch name (row 95 in hydro.fish) doesn't seem to work...

Experimenting with following settings

```fish
set --global hydro_color_prompt 94e2d5
set --global hydro_color_error f38ba8
set --global hydro_color_pwd b4befe
set --global hydro_color_git f9e2af
set --global hydro_color_duration 94e2d5
set --global hydro_multiline true

set --global hydro_prompt_prefix \n" "
set --global hydro_git_prefix " "
set --global hydro_pwd_prefix " "
set --global hydro_duration_prefix "󰅐 "
```

Prompt, pwd and duration seems to work as expected

**Comment by XelorR** [comment]
Now it seems to work as expected, created the pr: #52

**Comment by oliver-cfc** [comment]
> Now it seems to work as expected, created the pr: #52

Just want to say I've been using this for a short while now and it's working perfectly as far as I can tell (just hydro_color_beginning and hydro_prefix_beginning)

**Comment by jorgebucaran** [comment]
Good to know! Thanks 👍

**Comment by jorgebucaran** [comment]
Partially implemented in https://github.com/jorgebucaran/hydro/pull/52.
