### ISSUE TITLE
`Broken Pipe` Error gets printed when holding enter

### ISSUE THREAD

**Issue by vrishk** [jorgebucaran/hydro#6]
Thank you very much for this prompt!

When I hold down enter, it gives the following error:

```
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Setup:

```
OS: MacOS Big Sur
fish: version 3.1.2
```

<img width="896" alt="Screen Shot 2021-01-18 at 8 46 27 AM" src="https://user-images.githubusercontent.com/37949241/104868556-a9caa400-5969-11eb-9554-12a11170aca2.png">

**Comment by jorgebucaran** [comment]
Sorry, I can't reproduce on macOS running the latest Fish. Can you share your environment here?

```console
set
```

**Comment by vrishk** [comment]
I am running fish with the following fisher plugins:

```
jorgebucaran/fisher
fishgretel/fasd
PatrickF1/fzf.fish
jorgebucaran/hydro
```

My config.fish:

```
set -e fish_greeting

set hydro_color_pwd blue
set hydro_color_git yellow
set hydro_color_error red
set hydro_color_prompt 6DCC00
set hydro_color_duration $fish_color_normal

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval /Users/vishirishi/Software/miniconda3/bin/conda "shell.fish" "hook" $argv | source
# <<< conda initialize <<<
```

Would you need any other files?

**Comment by jorgebucaran** [comment]
Could you uninstall all the plugins, except for Fisher and Hydro (of course), comment out the Conda initialization code, and try again?

**Comment by jorgebucaran** [comment]
Please comment out the Conda initialization code and try again.

**Comment by vrishk** [comment]
Yeah it works perfectly now. Is the problem with Conda's fish init being unable to cope with the speed?

**Comment by jorgebucaran** [comment]
Try running Conda's initialization only if you're interactive, by adding this to your `config.fish`:

```fish
status is-interactive &&
  eval /Users/vishirishi/Software/miniconda3/bin/conda "shell.fish" "hook" $argv | source
```

**Comment by vrishk** [comment]
Thank you so much! It works perfectly now.
