### ISSUE TITLE
Hydro slowdown Fish's launch

### ISSUE THREAD

**Issue by Princesseuh** [jorgebucaran/hydro#7]
Even though Hydro is much faster than [Tide](https://github.com/IlanCosman/tide) at rendering the prompt, like advertised (measured using `time fish_prompt`)

Hydro:
```
Executed in  172,00 micros    fish           external
   usr time  159,00 micros  159,00 micros    0,00 micros
   sys time   15,00 micros   15,00 micros    0,00 micro
```

Tide:
```
Executed in    2,06 millis    fish           external
   usr time    2,04 millis    2,04 millis    0,00 micros
   sys time    0,01 millis    0,01 millis    0,00 micros
```

It comes with the downside that it slowdown the launch (or perhaps the shutdown?) of Fish by roughly 8-10ms (mesured using [hyperfine](https://github.com/sharkdp/hyperfine) with the command `fish -i -c "exit"`) on my machine:

Hydro: 
```
Benchmark #1: fish -i -c "exit"
  Time (mean ± σ):      24.7 ms ±   1.4 ms    [User: 20.1 ms, System: 6.0 ms]
  Range (min … max):    20.1 ms …  30.3 ms    102 runs
```

Tide:
```
Benchmark #1: fish -i -c "exit"
  Time (mean ± σ):      16.7 ms ±   1.1 ms    [User: 14.1 ms, System: 3.5 ms]
  Range (min … max):    11.8 ms …  18.6 ms    146 runs
```

This is with the default settings on Hydro and the Pure preset on Tide with few icons. I can reproduce those results by uninstalling / reinstalling both prompts. My `config.fish` file is available [here](https://github.com/Princesseuh/dotfiles/blob/master/fish/config.fish) if needed

**Comment by jorgebucaran** [comment]
Need for speed ey? I can't notice any difference using `time fish -c exit` between Hydro and `function fish_prompt; echo; end`. But I suppose Hyperfine can see things Fish's `time` can't. 

I suspect the problem is here:

https://github.com/jorgebucaran/hydro/blob/0c7e1beb17c8e33ecfa647b347dff60666279a6a/conf.d/hydro.fish#L101-L105

I was actually planning to remove all that because it always takes me a while to remember what I am doing there. The goal was to cache the color codes, in the hope that would make `fish_prompt` faster. 

Thanks for the detailed report!

**Comment by jorgebucaran** [comment]
Okay, I installed Hyperfine and followed your instructions and got this:

**Tide**
```
~/tank/hydro main
❯ hyperfine fish -i -c "exit" --warmup=10
Benchmark #1: fish
  Time (mean ± σ):       5.7 ms ±   0.5 ms    [User: 3.8 ms, System: 1.4 ms]
  Range (min … max):     5.3 ms …   9.0 ms    303 runs
```

**Hydro**

```
~/t/hydro main ❱ hyperfine fish -i -c "exit" --warmup=10
Benchmark #1: fish
  Time (mean ± σ):       5.6 ms ±   0.5 ms    [User: 3.6 ms, System: 1.5 ms]
  Range (min … max):     5.1 ms …   9.2 ms    395 runs
```

macOS Big Sur

**Comment by jorgebucaran** [comment]
I installed Hyperfine, followed your instructions, and this is what I got:

**Tide**
```
~/tank/hydro main
❯ hyperfine fish -i -c "exit" --warmup=10
Benchmark #1: fish
  Time (mean ± σ):       5.7 ms ±   0.5 ms    [User: 3.8 ms, System: 1.4 ms]
  Range (min … max):     5.3 ms …   9.0 ms    303 runs
```

**Hydro**

```
~/t/hydro main ❱ hyperfine fish -i -c "exit" --warmup=10
Benchmark #1: fish
  Time (mean ± σ):       5.6 ms ±   0.5 ms    [User: 3.6 ms, System: 1.5 ms]
  Range (min … max):     5.1 ms …   9.2 ms    395 runs
```

**Specs**

macOS Big Sur
MacBook Pro (15-inch, 2019)
Intel UHD Graphics 630 1536 MB
32 GB 2400 MHz DDR4
2.4 GHz 8コアIntel Core i9

**Comment by jorgebucaran** [comment]
I'm also running the latest Fish from HEAD (not 3.1.2).

**Comment by Princesseuh** [comment]
Hmm, that's weird (computers yay). I'll try a few things

Okay, so turns out running without `-i` makes the benchmarks much more closer so maybe it's something in my config?

**Tide**
```
Benchmark #1: fish
  Time (mean ± σ):      11.5 ms ±   1.1 ms    [User: 9.4 ms, System: 2.3 ms]
  Range (min … max):     7.0 ms …  13.4 ms    179 runs
```

**Hydro**
```
Benchmark #1: fish
  Time (mean ± σ):      11.1 ms ±   1.0 ms    [User: 8.9 ms, System: 2.4 ms]
  Range (min … max):     6.9 ms …  13.5 ms    198 runs
```

This is with `hyperfine fish -c "exit"`, adding a warmup doesn't change the results

**Comment by jorgebucaran** [comment]
Try commenting out everything in your `config.fish` just to be sure?

**Comment by Princesseuh** [comment]
Ah, I figured it out, it's not the `-i`, it depend on how I write the hyperfine command

Using `hyperfine 'fish -i -c "exit"'` (note the ' around the command):

**Hydro**
```
~ ❱ hyperfine 'fish -i -c "exit"'
Benchmark #1: fish -i -c "exit"
  Time (mean ± σ):      22.9 ms ±   1.4 ms    [User: 18.0 ms, System: 5.9 ms]
  Range (min … max):    19.4 ms …  26.9 ms    107 runs
```

**Tide**
```
❯ hyperfine 'fish -i -c "exit"'
Benchmark #1: fish -i -c "exit"
  Time (mean ± σ):      15.5 ms ±   1.3 ms    [User: 12.7 ms, System: 3.3 ms]
  Range (min … max):    10.7 ms …  18.4 ms    143 runs
```

Without the ' around the command:

**Hydro**
```
~ ❱ hyperfine fish -i -c "exit"
Benchmark #1: fish
  Time (mean ± σ):      10.9 ms ±   1.3 ms    [User: 8.6 ms, System: 2.5 ms]
  Range (min … max):     6.9 ms …  13.4 ms    201 runs
```
**Tide**
```
❯ hyperfine fish -i -c "exit"
Benchmark #1: fish
  Time (mean ± σ):      11.5 ms ±   1.2 ms    [User: 9.2 ms, System: 2.4 ms]
  Range (min … max):     7.3 ms …  14.6 ms    165 runs
```

**Comment by Princesseuh** [comment]
Oh wait I'm dumb, it doesn't mesure the rest of the command when I don't put the ' that's why the results are different LMAO

**Comment by jorgebucaran** [comment]
<img width="1282" alt="スクリーンショット 2021-01-20 3 58 07" src="https://user-images.githubusercontent.com/56996/105080249-e9150400-5ad3-11eb-809d-83c8ae880a03.png">

Can't reproduce the issue. I didn't even comment out my `config.fish` where I customize Hydro colors (which will trigger `--on-variable` handlers and do nothing in the case of Tide). I have absolutely nothing else in my `config.fish`.

**Comment by Princesseuh** [comment]
It's effectively the `-i` flag that cause the 10ms difference in my case, removing my config (apart from the part where I load fisher plugins) doesn't change this, neither does removing any functions that run on `fish_prompt` event. 

I'm gonna try on a completely empty config with all my plugins removed, sorry for the inconvenience 😅

**Comment by jorgebucaran** [comment]
No problem. By the way, are you using a custom `$fisher_path`? You don't need to [do this](https://github.com/Princesseuh/dotfiles/blob/762ac99631c3bbe3fcee747d9a3fdcea960ddff8/fish/config.fish#L26-L28) unless you have a custom `$fisher_path`, but I see no indication of that in your `config.fish`, hence the question.

**Comment by Princesseuh** [comment]
Removed my entire Fish folder so all the screenshots are with the base config of Fish (I'm using `fish, version 3.1.2` however, not HEAD), Fisher and the installed prompt in their base form (no customization on Tide)

Base prompt:

![image](https://user-images.githubusercontent.com/3019731/105081139-d06b0680-5a5f-11eb-85d9-3c3404b18ee3.png)

Hydro: 

![image](https://user-images.githubusercontent.com/3019731/105081241-e8db2100-5a5f-11eb-9ee7-9cb2abb299a4.png)

Tide:

![image](https://user-images.githubusercontent.com/3019731/105081397-23dd5480-5a60-11eb-9b35-a591a1e57725.png)

Trying out with HEAD of Fish, I get the more or less the same results (albeit everything seems a bit faster, cool stuff), still an unusual spike with Hydro with `-i`. I'm not sure what more I can provide than that, sorry! Here's a few random infos if anything can tip you off maybe: 

Config:
WM: Sway 1.5.1 (so Wayland)
Terminal: alacritty 0.6.0
CPU: i7-3930k
GPU: GTX 1080ti (using Nouveau)

> No problem. By the way, are you using a custom `$fisher_path`? You don't need to [do this](https://github.com/Princesseuh/dotfiles/blob/762ac99631c3bbe3fcee747d9a3fdcea960ddff8/fish/config.fish#L26-L28) unless you have a custom `$fisher_path`, but I see no indication of that in your `config.fish`, hence the question.

Yes, the variable is defined [here](https://github.com/Princesseuh/dotfiles/blob/762ac99631c3bbe3fcee747d9a3fdcea960ddff8/fish/conf.d/fisher.fish). I was originally hoping to have all the fisher stuff outside of `config.fish` but it turns out I needed plugins to be loaded at the end of `config.fish` for a reason I don't remember

**Comment by jorgebucaran** [comment]
Actually, just `hyperfine "fish -i -c exit"` is still correct (and easier to read). Did you comment out everything in your `config.fish`? It'd be nice if you could do that and try again.

**Comment by Princesseuh** [comment]
> Actually, just `hyperfine "fish -i -c exit"` is still correct (and easier to read)

True, I just mindlessly copy-pasted it (doesn't affect the results just in case you wonder)

> Did you comment out everything in your config.fish? It'd be nice if you could do that and try again.

These screenshots are using a completely vanilla Fish config (removed the entire fish config folder), so there's nothing to comment. Unless you mean on my normal configuration, in which case commenting everything did not change the results, neither did removing any functions that ran on prompt

**Comment by jorgebucaran** [comment]
I found it. The problem is here https://github.com/jorgebucaran/hydro/blob/0c7e1beb17c8e33ecfa647b347dff60666279a6a/conf.d/hydro.fish#L113

**Comment by jorgebucaran** [comment]
That part appears to be a code relic from an earlier shape of this prompt, but we no longer need it. We were running it twice!

As for `_hydro_pwd`, we can delay it until the `fish_prompt` event handler fires. 💯

**Comment by jorgebucaran** [comment]
Thank you, @Princesseuh! It's looking a lot better now.

![](https://user-images.githubusercontent.com/56996/105091448-2e8cfd80-5ae3-11eb-895a-aa27049b12fd.png)
