### ISSUE TITLE
What are the iTerm2 themes on screenshots?

### ISSUE THREAD

**Issue by x7a** [jorgebucaran/hydro#8]
Sorry if this is unrelated, but I like how Hydro looks combined with them.

**Comment by jorgebucaran** [comment]
Sorry, I don't remember and I don't keep the files around anymore. I'm using iTerm2's ayu with Fish ayu theme at the moment.

<img width="1006" alt="スクリーンショット 2021-03-05 1 12 43" src="https://user-images.githubusercontent.com/56996/109993773-fae2fb80-7d4f-11eb-8f89-908209cd05d7.png">
